server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**

  security:
    user:
      name: test@naver.com
      password: 1q2w3e4r!
    oauth2:
      client:
        registration:
          google:
            clientId: 108269795527-opd4iqrk4vi5u3d5t2ruvhmed36v960e.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
          naver:
            clientId: QXsTU1iNHPCXToqXOo4P
            clientSecret: AwhKuSJnql
            scope:
              - email
              - name
            clientName: Naver
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8000/login/oauth2/code/naver
        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://shc-db.cgogdkhaohzu.ap-northeast-2.rds.amazonaws.com/stussy-20220930
    username: admin
    password: 1q2w3e4r

mybatis:
  mapper-locations:
    - /mappers/*.xml
