server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**

  security:
    user:
      name: test@naver.com
      password: 1q2w3e4r!

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://shc-db.cgogdkhaohzu.ap-northeast-2.rds.amazonaws.com/stussy-20220930
    username: admin
    password: 1q2w3e4r

mybatis:
  mapper-locations:
    - /mappers/*.xml

file:
  path: C:/HeeCheol/springboot/stussy-clone-20220930-SHC/src/main/resources/static/upload/